# See https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "clinvoice_schema"
version = "0.8.0"
authors = ["Iron-E <code.iron.e@gmail.com>"]
description = "Data structures for CLInvoice."

edition = "2021"
license = "GPL3"
readme = "README.md"
repository = "https://www.github.com/Iron-E/clinvoice_schema"

[dependencies]
# Async
futures = "0.3"

# CLInvoice
clinvoice_finance = {branch = 'release/0.3', git = 'https://github.com/Iron-E/clinvoice_finance'}

# Date/Time
chrono = {features = ["serde"], version = "0.4"}

# Errors
thiserror = "1"

# Perf
lazy_static = "1"

# Serialization
humantime-serde = "1"
serde = {optional = true, version = "1"}

[dev-dependencies]
pretty_assertions = "1"

[features]
default = []
serde_support = ["clinvoice_finance/serde_support", "serde/derive"]
